name: Publish Package to npmjs

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npm-publish

    permissions:
      contents: read
      id-token: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '25.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish to npm
        run: npm publish --access public --provenance
